name: build 

on:
  push:
    branches:
      - master
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: 
  contents: read 

jobs: 
  test: 
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }} 
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: false 
      matrix: 
        node-version: [20.x, 22.x, 24.x] 
        os: [ubuntu-latest, windows-latest, macos-latest] 

    steps: 
    - uses: actions/checkout@v5 
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v6 
      with: 
        cache: 'pnpm' 
        node-version: ${{ matrix.node-version }} 

    - name: pnpm install 
      run: pnpm install --frozen-lockfile

    - name: pnpm test 
      run: pnpm test 

    - name: pnpm run check 
      run: pnpm run check

    - name: pnpm build
      run: pnpm build